### ISSUE TITLE
WebSocket output

### ISSUE THREAD

**Issue by davidwallis** [Loxone/LxCommunicator.NET#12]
I suspect this is more something with my config but why am I getting updates all the time for the override?

![image](https://user-images.githubusercontent.com/13855486/121602945-f5c4d500-ca3f-11eb-8632-31a32a620739.png)

This maps to:

![image](https://user-images.githubusercontent.com/13855486/121603031-142ad080-ca40-11eb-83db-953858ccdff1.png)

![image](https://user-images.githubusercontent.com/13855486/121603091-299ffa80-ca40-11eb-9db8-4e6d83591542.png)

![image](https://user-images.githubusercontent.com/13855486/121603125-37ee1680-ca40-11eb-9a2e-406ad886e654.png)

![image](https://user-images.githubusercontent.com/13855486/121603257-623fd400-ca40-11eb-937f-c2545f066c64.png)

![image](https://user-images.githubusercontent.com/13855486/121603303-771c6780-ca40-11eb-82fd-500da7b1df83.png)

Hope that helps - just interested in why the frequency and what these updates are representing?

Thanks

**Comment by idoodler** [comment]
Hi @davidwallis3101 

You currently have an active override timer running. So there is an active countdown active. These messages represent the current remaining time.

Greetings,
David

**Comment by davidwallis** [comment]
Thanks, that makes sense 👍
