### ISSUE TITLE
.NET 6.0 Support

### ISSUE THREAD

**Issue by SvenVandenbrande** [Loxone/LxCommunicator.NET#13]
@LxWolfgang  Should we use a new branch for .NET 6.0 support or?

**Comment by loxone-mahriwo** [comment]
Hello
the projects are set up as [multiple-target-frameworks-project-file](https://docs.microsoft.com/en-us/nuget/create-packages/multiple-target-frameworks-project-file). You can open a pull request to add support for .NET 6.0.
Later I will prepare a NuGet Package update, including these changes.

**Comment by SvenVandenbrande** [comment]
@LxWolfgang I did some first tests and it looks like it's working just with referencing the new .NET 6.0 framework

**Comment by SvenVandenbrande** [comment]
@LxWolfgang can you also publish the new nuget package?

**Comment by loxone-mahriwo** [comment]
The Nuget Package will be updated this week.

**Comment by loxone-mahriwo** [comment]
I just submitted version 0.9.5 which includes the support for Net6.0.
As soon as NuGet has validated the package it should be available.
