### ISSUE TITLE
How to send KeepAlive

### ISSUE THREAD

**Issue by CalDymos** [Loxone/LxCommunicator.NET#4]
How do I send the "keepAlive" message to the Miniserver to keep the connection alive?
I've tried 

await client.SendWebservice(new WebserviceRequest<string>("keepalive", EncryptionType.None));

but it doesn't seem to work.

**Comment by CalDymos** [comment]
I made it possible that at least keepalive is sent once and the Miniserver confirms it.
However, no more status updates are received after that (**Client_OnReceiveEventTable is no longer called**)


using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Loxone.Communicator;
using Loxone.Communicator.Events;
using System.Timers;
using System.Diagnostics;

namespace LxCommunicator.NET.Example.Websocket {
	class Program {
		static WebsocketWebserviceClient client;
		static Timer KeepAliveTimer;
		private const int keepAlivePeriod = 240; // Value in seconds , set to 4 minutes, server timeout is 5 minutes
		static bool keepAliveSent;
		private const string CMD_KEEPALIVE = "keepalive";
		static bool LinkAktive;
		private static bool StatusUpdateIsEnabled;

		static async Task Main(string[] args) {
			using (client = new WebsocketWebserviceClient("testminiserver.loxone.com", 7777, 2, "098802e1-02b4-603c-ffffeee000d80cfd", "LxCommunicator.NET.Websocket")) {
				using (TokenHandler handler = new TokenHandler(client, "app")) {
					handler.SetPassword("LoxLIVEpasswordTest");
					client.OnReceiveEventTable += Client_OnReceiveEventTable;
					client.OnAuthenticated += Client_OnAuthenticated;
					await client.Authenticate(handler);

					KeepAliveTimer = new Timer((keepAlivePeriod * 1000));
					KeepAliveTimer.Elapsed += new System.Timers.ElapsedEventHandler(KeepAliveTimer_Tick);
					KeepAliveTimer.AutoReset = false;
					KeepAliveTimer.Enabled = true;

					string result = (await client.SendWebservice(new WebserviceRequest<string>("jdev/sps/enablebinstatusupdate", EncryptionType.None))).Value;
					StatusUpdateIsEnabled = System.Convert.ToBoolean(System.Convert.ToInt32(result));
					Console.ReadLine();
					await handler.KillToken();
				}
			}
		}

		private static void Client_OnAuthenticated(object sender, ConnectionAuthenticatedEventArgs e) {
			Console.WriteLine("Successfully authenticated!");
			LinkAktive = true;
		}

		private static void Client_OnReceiveEventTable(object sender, EventStatesParsedEventArgs e) {
			foreach (EventState state in e.States) {
				Console.WriteLine(state.ToString());
			}
		}

		private static async void KeepAliveTimer_Tick(object source, ElapsedEventArgs e)
		{
			if (client != null && LinkAktive && StatusUpdateIsEnabled && !keepAliveSent)
			{
				keepAliveSent = true;
				WebserviceRequest rq = new WebserviceRequest(CMD_KEEPALIVE, EncryptionType.None);
				WebserviceResponse wr;
				wr = await client.SendWebservice(rq); 
				if (wr != null && wr.Header.Type == MessageType.KeepAlive)
				{
					Debug.WriteLine("Keepalive answer received !");
				}
				keepAliveSent = false;
				KeepAliveTimer.Start();
			}
		}

	}
}

**Comment by loxone-mahriwo** [comment]
@CalDymos Unfortunate at the moment sending keep alives was not possible. Because the keepalive response wasn't handle correctly and caused a NullReferenceException internally. This also caused the MessageHandler to stop and therefor no event or webservice responses are processed.
With the fix of https://github.com/Loxone/LxCommunicator.NET/issues/3 the exception isn't thrown anymore. But the KeepAlive will still not work as expected, because unfortunate responses with MessageType.KeepAlive arn't forwarded correctly to the WebserviceRequest.SendWebservice. This will cause the SendWebserivce to run into an timeout.

Even if the WebserviceRequest is running into an timeout the Miniserver probably will receive and process the KeepAlive request.  Only the KeepAlive response of the Miniserver is not processed.
Please notice that the changes for the mentioned pull request are not published in the nuget package.

**Comment by loxone-mahriwo** [comment]
To resolve this issue a KeepAlive Handler should be implemented into the WebsocketWebsesrviceHandler.
Also sending a KeepAlive using WebserviceRequest.SendWebservice should be supported.

**Comment by loxone-mahriwo** [comment]
With the linked pull request a Keepalive Handler was implemented into WebsocketWebserviceHandler.
If a Keepalive should be send and in which intervals can also be configured.
Every Keepalive request will trigger the OnKeepalive event. The KeepaliveEventArgs are giving feedback if the keepalive was successful. The event can be used to close the connection if the Miniserver is not responding anymore, also the connection speed can be determined as descripted in the [API documentation](https://www.loxone.com/dede/kb/api/).
