### ISSUE TITLE
.NET Standard or .NET Core Version

### ISSUE THREAD

**Issue by SvenVandenbrande** [Loxone/LxCommunicator.NET#6]
Is it possible to create a .NET Standard version? 
Or an .NET Core Version?

Can I create a pull request for that? Or do you guys prefer that I create a new project.
And rework to .NET Standard?

@LxWolfgang

**Comment by loxone-mahriwo** [comment]
Hello,
@SvenVandenbrande yes porting the code could be an enrichment for many future projects in the community. (Especially if you are following the development of [.Net 5.0 (.Net Core vNext)](https://devblogs.microsoft.com/dotnet/introducing-net-5/)). We want to avoid the creation of multiple community forks of the project, therefore we are open for pull requests.

As descripted in our [disclaimer ](https://github.com/Loxone/LxCommunicator.NET#disclaimer) we still not provide support. But we are happy to support the further development of the project.

**Comment by SvenVandenbrande** [comment]
@LxWolfgang Indeed the new .NET 5.0 (only 1 .net framework) is a great new feature. It will be easier for everybody. :)
I am aware that Loxone doesn't give support for it. 

I will only use it to write some application to send monitoring data to a database. So I can create reports on that.
So if something goes wrong. It's not that bad. I will only lose some data. I will not make decisions (not yet :) ) on the data that's coming.
But I think this option is the best way to do that. So the SD is not impacted.

**Comment by SvenVandenbrande** [comment]
@LxWolfgang It's maybe an idea to create a branch for a new .NET version? So I don't need to create a pull request against the master branch? And you can still have the different packages..

**Comment by loxone-mahriwo** [comment]
@SvenVandenbrande I just added branches. DotNetSupport is reserved for this purpose. I hope I set up the rules correctly and you are able to access this branch.

Basic branch rules:
master -> only releases and only the Development branch can be merged into the master branch.
Development -> current development until a new release

**Comment by SvenVandenbrande** [comment]
Pull request #7 is normally a working .NET Standard 2.1 library. :)
Didn't do big tests. But the first tests looks ok.

**Comment by loxone-mahriwo** [comment]
@SvenVandenbrande I've committed all the needed changes into Development. I will create the new NuGet package and also commit the changes into the master Branch

**Comment by loxone-mahriwo** [comment]
I published the version 0.9.4 just now.
